#!/usr/bin/python

import compileall
import os
import sys


def main(args):
	repoPath = os.path.dirname(os.path.dirname(args[0]))
	srcPath = os.path.join(repoPath, 'src')
	compileall.compile_dir(srcPath, force=1)

	return 0


if __name__ == '__main__':
	sys.exit(main(sys.argv))
